version: '3.9'

services:
  backend:
    image: ibmjava:latest
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - "./build/libs:/usr/app"
    command:  ['java', '-jar', '/usr/app/auto-atendimento-JuMarket-0.0.1-SNAPSHOT.jar']
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: