CREATE TABLE cart_item (
  id BIGINT AUTO_INCREMENT NOT NULL,
   cart_id BIGINT NULL,
   product_id BIGINT NULL,
   amount INT NOT NULL,
   CONSTRAINT pk_cartitem PRIMARY KEY (id)
);

ALTER TABLE cart_item ADD CONSTRAINT FK_CARTITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_item ADD CONSTRAINT FK_CARTITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);